
// https://api.krisinformation.se/v3/news
// https://images-api.nasa.gov
// https://api.krisinformation.se/v3/news?format=xml 
// https://images-api.nasa.gov/search?q=jwts
// https://api.krisinformation.se/v3/notifications

//https://api.krisinformation.se/v3/testvmas HTTP/1.1

GET https://api.krisinformation.se/v3/news?allCounties=true&days=60